baseURL = "/"
title = "Tiationg's Portfolio"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

enableGitInfo = true

[outputs]
home = ["HTML"]
section = ["HTML"]
page = ["HTML"]

[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
taxonomyCloud = ["tags", "categories"]

taxonomyCloudTitle = ["Tag Cloud", "Categories"]

taxonomyPageHeader = ["tags", "categories"]

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[languages]
[languages.en]
languageName ="English"
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

[params]
prism_syntax_highlighting = false
timeout = "60s"

[params.copyright]
authors = "Tiationg Kho. All rights reserved."

[params.ui]
navbar_translucent_over_cover_disable = false

[params.ui.readingtime]
enable = false

[module]
  # Uncomment the next line to build and serve using local docsy clone declared in the named Hugo workspace:
  # workspace = "docsy.work"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
